title: Wgr1984 github pages
description: Wgr1984 github pages, documentation and blog
remote_theme: just-the-docs

url: https://wgr1984.github.io

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
